### ISSUE TITLE
MSN-Hard dataset issue

### ISSUE THREAD

**Issue by Anqw** [stelzner/srt#4]
Thanks for your wonderful work, I can not find the MSN-Hard dataset used in osrt, how should I download the MSN-Hard dataset？

**Comment by stelzner** [comment]
Hi, check the new OSRT repository for instructions: https://github.com/stelzner/osrt
The only significant difference between OSRT's MSN-hard and SRT's MSN is that the OSRT dataset includes instance segmentations, which are used to evaluate object segmentation performance.  Since SRT isn't concerned with that, I haven't added that dataset to this repo.
